from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'


# Colors
PRIMARY_COLOR = '#912ffa'
DARKER_PRIMARY_COLOR = '#5a1c9c'
DARKEST_PRIMARY_COLOR = '#3f146e'


# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 400

